version: "3.9"

services:
  sonarqube:
    container_name: "sonarqube-container"        
    image: "sonarqube:9.9.2-community"
    volumes:
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/data:/opt/sonarqube/data
    expose:
      - "9000"
    ports:
      - "9000:9000"
  
  web:
    build: ./front/
    container_name: web
    ports:
      - "3000:3000"
    command: npm start  
    volumes:
      - "./front/:/app"  
      - "/app/node_modules"
    environment:
      - REACT_APP_BASEURL=http://localhost:5000 

  api:
    build: ./Back/
    container_name: api
    ports:
      - "5000:5000"
    command: npm start  
    environment:
      MONGO_URI: mongodb://db:27017/firstProject
      JWT_KEY: jawher
    volumes:
      - "./Back/:/app"  
      - "/app/node_modules"
  db: 
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: firstProject
    ports:
      - 27018:27017
    volumes:
      - db-data:/data/db

volumes:
  db-data: {}        
   
  