export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const GET_ONE_RESERVATION = "GET_ONE_RESERVATION";
export const GET_MY_RESERVATIONS = "GET_MY_RESERVATIONS";
export const GET_SEARCH_RESERVATIONS = "GET_SEARCH_RESERVATIONS";
export const IS_LOADING = "IS_LOADING";
